name: Build/release

on:
  push:
    branches:
      - main # Yalnızca 'main' dalına push yapıldığında çalışır.

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx electron-builder --dir && npx electron-builder --win --x64

  release:
    runs-on: windows-latest

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE file to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/make/squirrel.windows/x64/*.exe
          asset_name: electron-app
          asset_content_type: application/octet-stream